### ISSUE TITLE
cant get it working

### ISSUE THREAD

**Issue by tarkandinc** [jpetazzo/griode#13]
i have some sound but on rows 1, 3, 5, and seven (from bottom), the buttons on colom 4 and 5 doesnt work

**Comment by jpetazzo** [comment]
Oh that's weird! Which LaunchPad are you using? And are you in "Note" mode?

**Comment by tarkandinc** [comment]
i am using launchpad pro and yes using in note mode.

**Comment by jpetazzo** [comment]
Definitely weird! One thing you can do (if you still want to investigate) would be to start griode by raising the log level.

If you run it manually (because you run from a computer, or SSH into a Pi...) you can do

```bash
LOG_LEVEL=DEBUG ./griode.py
```

And you should get (a lot of) extra debug messages. Perhaps it'll give additional insights about what's happening (e.g. if the MIDI messages don't arrive or whatever).
