### ISSUE TITLE
I Can t hear any notes

### ISSUE THREAD

**Issue by BabyYodaCanCode** [jpetazzo/griode#15]
This project sound cool, but for the moment doesn't work. 
My Hardware Is a clone of RaspberryPi called Tritium H2+ with 4 core arm7 and 512 Mb of RAM with ARMBIAN OS, and I bought a new LAUNCHPAD X.
I installed all software and I start griode, but It didn' t sound. I have all light on on my Lauinchpad X but no sound.
I use headphone on that.

Just want to know, after started command ./griode.py Launchpad should sound ...  

 Maybe I can try this project on regular laptop with linux and then re try on my tritium.

Thank you.

**Comment by jpetazzo** [comment]
Hi!

The code detects the type of LaunchPad by looking at the MIDI port name.
Depending on the name of the port, it uses a different adapter class (because the exact MIDI messages change a bit between different models of LaunchPad).

The detection is done here:
https://github.com/jpetazzo/griode/blob/master/griode.py#L54

It should be relatively easy to add support for the LaunchPad X (assuming that the MIDI messages are not too different).

If you know a bit of Python and want to try, I'm happy to provide more details!

**Comment by jpetazzo** [comment]
Closing this issue in favor of #16.
