### ISSUE TITLE
Feature request - documentation

### ISSUE THREAD

**Issue by kengberg** [jpetazzo/griode#6]
Pressing user2 and then up-arrow twice, brings me to this:

![2018-07-27 14 30 31](https://user-images.githubusercontent.com/10281185/43320761-dce14d56-91a9-11e8-8b1b-ab6fc5912c89.jpg)

So the top key is for turning on and off the arpeggiator.

We'd really like to know what the others are for ;-)

**Comment by jpetazzo** [comment]
OK, from top to bottom:

- turn arpeggiator on/off (as you figured out :))
- note order; from left to right:
  - FIRST: when you press a note, the arpeggiator will play it as soon as possible (at the next tick)
  - LAST: when you press a note, it will be played after all other notes
  - ASCENDING: the arpeggiator will spell out notes in ascending order, regardless of when you pressed them
  - DESCENDING: same but descending order
  - BOUNCING: arpeggiator will go from lower note to higher note, then back down, and repeat
- motif mode: this is related to the motif screen (DOWN DOWN from the setup screen). I need to record a video showing this...
  - DISABLED: motif will be mapped to octaves (like in my "80s synth bass" demo)
  - SCALE: motif will be mapped to steps in the scale
  - BUFFER: motif will be mapped to the different pressed notes
- scale key: this is how the base note is determined when motif is in SCALE mode

Note order is pretty easy, but Motif and Scale are more complicated.

The reason why I haven't recorded a video yet, is because I consider these features to be "beta" (I don't know if they really make sense yet and perhaps they need to be tweaked...)

But perhaps I should record videos anyway because for now they're probably very obscure!

Does that help?

**Comment by kengberg** [comment]
That helped a lot. Thank you for clarifying.
